-- Seed breeds table
INSERT INTO breeds (name_it, name_en, slug, group_fci, group_name_it, origin_country, size_category, is_italian_breed, is_popular) VALUES
  ('Cane Corso',' Cane Corso','cane-corso',2,'Molossoidi','Italia','grande',true,true),
  ('Lagotto Romagnolo',' Lagotto Romagnolo','lagotto-romagnolo',8,'Cani da riporto e da acqua','Italia','media',true,true),
  ('Spinone Italiano',' Italian Spinone','spinone-italiano',7,'Cani da ferma','Italia','grande',true,true),
  ('Bracco Italiano',' Italian Bracco','bracco-italiano',7,'Cani da ferma','Italia','grande',true,true),
  ('Pastore Maremmano-Abruzzese',' Maremma Sheepdog','pastore-maremmano-abruzzese',1,'Cani da pastore','Italia','gigante',true,true),
  ('Segugio Italiano a pelo raso',' Italian Hound','segugio-italiano-pelo-raso',6,'Segugi','Italia','media',true,false),
  ('Volpino Italiano',' Italian Volpino','volpino-italiano',5,'Cani di tipo Spitz','Italia','piccola',true,false),
  ('Cirneco dell''Etna',' Cirneco dell''Etna','cirneco-dell-etna',5,'Cani primitivi','Italia','media',true,false),
  ('Bolognese',' Bolognese','bolognese',9,'Cani da compagnia','Italia','piccola',true,false),
  ('Maltese',' Maltese','maltese',9,'Cani da compagnia','Italia','piccola',true,true),
  ('Pastore Bergamasco',' Bergamasco Shepherd','pastore-bergamasco',1,'Cani da pastore','Italia','grande',true,false),
  ('Mastino Napoletano',' Neapolitan Mastiff','mastino-napoletano',2,'Molossoidi','Italia','gigante',true,true),
  ('Levriero Italiano',' Italian Greyhound','levriero-italiano',10,'Levrieri','Italia','piccola',true,false),
  ('Labrador Retriever',' Labrador Retriever','labrador-retriever',8,'Cani da riporto','Regno Unito','grande',false,true),
  ('Golden Retriever',' Golden Retriever','golden-retriever',8,'Cani da riporto','Regno Unito','grande',false,true),
  ('Pastore Tedesco',' German Shepherd','pastore-tedesco',1,'Cani da pastore','Germania','grande',false,true),
  ('Bulldog Francese',' French Bulldog','bulldog-francese',9,'Cani da compagnia','Francia','piccola',false,true),
  ('Barboncino',' Poodle','barboncino',9,'Cani da compagnia','Francia','media',false,true),
  ('Chihuahua',' Chihuahua','chihuahua',9,'Cani da compagnia','Messico','piccola',false,true),
  ('Yorkshire Terrier',' Yorkshire Terrier','yorkshire-terrier',3,'Terrier','Regno Unito','piccola',false,true),
  ('Jack Russell Terrier',' Jack Russell Terrier','jack-russell-terrier',3,'Terrier','Regno Unito','piccola',false,true),
  ('Boxer',' Boxer','boxer',2,'Molossoidi','Germania','grande',false,true),
  ('Rottweiler',' Rottweiler','rottweiler',2,'Molossoidi','Germania','grande',false,true),
  ('Dobermann',' Doberman Pinscher','dobermann',2,'Pinscher e Schnauzer','Germania','grande',false,true),
  ('Border Collie',' Border Collie','border-collie',1,'Cani da pastore','Regno Unito','media',false,true),
  ('Cavalier King Charles Spaniel',' Cavalier King Charles Spaniel','cavalier-king-charles-spaniel',9,'Cani da compagnia','Regno Unito','piccola',false,true),
  ('Cocker Spaniel Inglese',' English Cocker Spaniel','cocker-spaniel-inglese',8,'Cani da cerca','Regno Unito','media',false,true),
  ('Beagle',' Beagle','beagle',6,'Segugi','Regno Unito','media',false,true),
  ('Bassotto',' Dachshund','bassotto',4,'Bassotti','Germania','piccola',false,true),
  ('Shih Tzu',' Shih Tzu','shih-tzu',9,'Cani da compagnia','Cina','piccola',false,true),
  ('Pastore Australiano',' Australian Shepherd','pastore-australiano',1,'Cani da pastore','Stati Uniti','media',false,true),
  ('Husky Siberiano',' Siberian Husky','husky-siberiano',5,'Cani di tipo Spitz','Russia','media',false,true),
  ('Bulldog Inglese',' English Bulldog','bulldog-inglese',2,'Molossoidi','Regno Unito','media',false,true),
  ('Setter Irlandese',' Irish Setter','setter-irlandese',7,'Cani da ferma','Irlanda','grande',false,false),
  ('Setter Inglese',' English Setter','setter-inglese',7,'Cani da ferma','Regno Unito','grande',false,false),
  ('Weimaraner',' Weimaraner','weimaraner',7,'Cani da ferma','Germania','grande',false,false),
  ('Alano',' Great Dane','alano',2,'Molossoidi','Germania','gigante',false,true),
  ('San Bernardo',' Saint Bernard','san-bernardo',2,'Molossoidi','Svizzera','gigante',false,false),
  ('Bovaro del Bernese',' Bernese Mountain Dog','bovaro-del-bernese',2,'Bovari Svizzeri','Svizzera','gigante',false,true),
  ('Akita Inu',' Akita Inu','akita-inu',5,'Cani di tipo Spitz','Giappone','grande',false,true),
  ('Shiba Inu',' Shiba Inu','shiba-inu',5,'Cani di tipo Spitz','Giappone','piccola',false,true),
  ('Schnauzer Nano',' Miniature Schnauzer','schnauzer-nano',2,'Pinscher e Schnauzer','Germania','piccola',false,true),
  ('Dalmata',' Dalmatian','dalmata',6,'Segugi','Croazia','grande',false,true),
  ('Pastore Belga Malinois',' Belgian Malinois','pastore-belga-malinois',1,'Cani da pastore','Belgio','grande',false,true),
  ('Terranova',' Newfoundland','terranova',2,'Molossoidi','Canada','gigante',false,false),
  ('Bichon Frisé',' Bichon Frisé','bichon-frise',9,'Cani da compagnia','Francia','piccola',false,true),
  ('Pomerania',' Pomeranian','pomerania',5,'Cani di tipo Spitz','Germania','piccola',false,true),
  ('Carlino',' Pug','carlino',9,'Cani da compagnia','Cina','piccola',false,true),
  ('Cane da Pastore Scozzese (Collie)',' Rough Collie','collie',1,'Cani da pastore','Regno Unito','grande',false,false),
  ('Whippet',' Whippet','whippet',10,'Levrieri','Regno Unito','media',false,false),
  ('Samoiedo',' Samoyed','samoiedo',5,'Cani di tipo Spitz','Russia','media',false,true),
  ('Springer Spaniel Inglese',' English Springer Spaniel','springer-spaniel-inglese',8,'Cani da cerca','Regno Unito','media',false,false),
  ('Pointer Inglese',' English Pointer','pointer-inglese',7,'Cani da ferma','Regno Unito','grande',false,false)
ON CONFLICT (slug) DO NOTHING;