/**
 * Types for the enriched breed dataset (src/data/razze-enriched.json).
 * Generated by scripts/enrich-breeds.mjs — do not edit manually.
 * To add missing data for a breed, edit scripts/manual-overrides.json.
 */

export interface QuizAttributes {
  /** 1 (low) – 5 (high). Source: AKC */
  energy: number | null;
  /** 1 (stubborn) – 5 (eager to please). Source: AKC */
  trainability: number | null;
  /** 1 (minimal) – 5 (heavy). Source: AKC */
  shedding: number | null;
  /** 1 (minimal) – 5 (frequent). Source: AKC */
  grooming: number | null;
  /** 1 (quiet) – 5 (vocal). Source: AKC */
  barking: number | null;
  /** 1 (not recommended) – 5 (great). Source: AKC */
  good_with_children: number | null;
  /** 1 (not recommended) – 5 (great). Source: AKC */
  good_with_other_dogs: number | null;
  /** 1 (reserved) – 5 (very open). Source: AKC */
  good_with_strangers: number | null;
  /** 1 (serious) – 5 (very playful). Source: AKC */
  playfulness: number | null;
  /** 1 (relaxed) – 5 (very protective). Source: AKC */
  protectiveness: number | null;
  /** 1 (low) – 5 (highly adaptable). Source: AKC */
  adaptability: number | null;
  /** 1 (low) – 5 (high). Source: AKC */
  mental_stimulation_needs: number | null;
}

export interface BreedSources {
  /** Always present. FCI official breed registry. */
  fci: string;
  /** Present if Italian description was found. */
  description_it?: string;
  /** Present if English description was found (fallback). */
  description_en?: string;
  /** Present if photo was found. */
  photo?: string;
  /** Present if quiz attributes were found. */
  quiz_attributes?: string;
}

export interface RazzaEnricched {
  // ── FCI core (authoritative) ──────────────────────────────────────────────
  /** Official FCI breed number */
  fci_id: number;
  name_it: string;
  name_en: string;
  slug: string;
  group_fci: number;
  group_name_it: string;
  size_category: "piccola" | "media" | "grande" | "gigante";
  origin_country: string;
  is_italian_breed: boolean;
  is_popular: boolean;
  /** Link to the official FCI breed page */
  fci_url: string;

  // ── Descriptions ──────────────────────────────────────────────────────────
  /** Italian prose description. Source: Italian Wikipedia (CC BY-SA). Null if not found. */
  description_it: string | null;
  /** English description fallback. Source: dogapi.dog. Null if not found. */
  description_en?: string | null;

  // ── Photo ─────────────────────────────────────────────────────────────────
  /** Photo URL. Source: Wikimedia Commons (CC BY-SA). Null if not found. */
  photo_url: string | null;
  /** Photo credit/license string to display to users */
  photo_credit: string | null;
  /** Link to the Italian Wikipedia page for attribution */
  wikipedia_url_it: string | null;

  // ── Physical data ─────────────────────────────────────────────────────────
  /** Minimum weight in kg. Source: dogapi.dog. Null if not found. */
  weight_min_kg: number | null;
  /** Maximum weight in kg. Source: dogapi.dog. Null if not found. */
  weight_max_kg: number | null;
  /** Minimum lifespan in years. Source: dogapi.dog. Null if not found. */
  lifespan_min: number | null;
  /** Maximum lifespan in years. Source: dogapi.dog. Null if not found. */
  lifespan_max: number | null;
  /** Whether the breed is considered hypoallergenic. Source: dogapi.dog. Null if unknown. */
  hypoallergenic: boolean | null;

  // ── Quiz attributes ───────────────────────────────────────────────────────
  /** Structured 1–5 scores for breed matchmaking quiz. Source: AKC. Null if not found. */
  quiz_attributes: QuizAttributes | null;

  // ── Source attribution (display to users) ─────────────────────────────────
  /** Per-field source URLs and labels */
  sources: BreedSources;
}
