/**
 * Types for the enriched breed dataset (src/data/razze-enriched.json).
 * Generated by scripts/enrich-breeds.mjs — do not edit manually.
 * To add missing data for a breed, edit scripts/manual-overrides.json.
 */

// ── Seeker-oriented breed attributes ────────────────────────────────────────

export type CoatType = "corto" | "medio" | "lungo" | "duro" | "riccio" | "senza_pelo" | "doppio";

export type PrimaryUse =
  | "compagnia"
  | "guardia"
  | "caccia"
  | "sport"
  | "pastorizia"
  | "terapia"
  | "lavoro"
  | "slitta";

export interface SeekerAttributes {
  // Physical
  /** Minimum adult height at withers in cm */
  height_min_cm: number;
  /** Maximum adult height at withers in cm */
  height_max_cm: number;
  /** Coat type */
  coat_type: CoatType;
  /** 1 (minimal) – 5 (heavy drooler) */
  drooling: number;
  /** Common coat colors in Italian */
  coat_colors: string[];

  // Lifestyle
  /** 1 (low, ~20min/day) – 5 (very high, 90+ min/day) */
  exercise_needs: number;
  /** 1 (not suitable) – 5 (ideal for apartments) */
  apartment_suitable: number;
  /** 1 (cannot be left alone) – 5 (handles 8+ hours) */
  alone_tolerance: number;
  /** 1 (not recommended) – 5 (ideal for beginners) */
  first_time_owner: number;

  // Environment
  /** 1 (very low) – 5 (excellent) */
  heat_tolerance: number;
  /** 1 (very low) – 5 (excellent) */
  cold_tolerance: number;

  // Health
  /** 2-5 common health concerns in Italian */
  health_issues: string[];

  // Purpose
  /** Primary uses for this breed */
  primary_use: PrimaryUse[];
}

export interface BreedSources {
  /** Always present. FCI official breed registry. */
  fci: string;
  /** Present if Italian description was found. */
  description_it?: string;
  /** Present if English description was found (fallback). */
  description_en?: string;
  /** Present if photo was found. */
  photo?: string;
  /** Present if seeker attributes were generated. */
  seeker_attributes?: string;
}

export interface RazzaEnricched {
  // ── FCI core (authoritative) ──────────────────────────────────────────────
  /** Official FCI breed number */
  fci_id: number;
  name_it: string;
  name_en: string;
  slug: string;
  group_fci: number;
  group_name_it: string;
  size_category: "piccola" | "media" | "grande" | "gigante";
  origin_country: string;
  is_italian_breed: boolean;
  is_popular: boolean;
  /** Link to the official FCI breed page */
  fci_url: string;

  // ── Descriptions ──────────────────────────────────────────────────────────
  /** Italian prose description. Source: Italian Wikipedia (CC BY-SA). Null if not found. */
  description_it: string | null;
  /** English description fallback. Source: dogapi.dog. Null if not found. */
  description_en?: string | null;

  // ── Photo ─────────────────────────────────────────────────────────────────
  /** Photo URL. Source: Wikimedia Commons (CC BY-SA). Null if not found. */
  photo_url: string | null;
  /** Photo credit/license string to display to users */
  photo_credit: string | null;
  /** Link to the Italian Wikipedia page for attribution */
  wikipedia_url_it: string | null;

  // ── Physical data ─────────────────────────────────────────────────────────
  /** Minimum weight in kg. Source: dogapi.dog. Null if not found. */
  weight_min_kg: number | null;
  /** Maximum weight in kg. Source: dogapi.dog. Null if not found. */
  weight_max_kg: number | null;
  /** Minimum lifespan in years. Source: dogapi.dog. Null if not found. */
  lifespan_min: number | null;
  /** Maximum lifespan in years. Source: dogapi.dog. Null if not found. */
  lifespan_max: number | null;
  /** Whether the breed is considered hypoallergenic. Source: dogapi.dog. Null if unknown. */
  hypoallergenic: boolean | null;

  // ── Seeker attributes ─────────────────────────────────────────────────────
  /** Structured attributes for breed discovery and filtering. Null if not yet generated. */
  seeker_attributes: SeekerAttributes | null;

  // ── Source attribution (display to users) ─────────────────────────────────
  /** Per-field source URLs and labels */
  sources: BreedSources;
}
